 
blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://discord.gg/gREP69pH
    about: For general community discussions about project in Discord.
    #  - name: Security Reports
    #url: todo, add when okd
    #about: Please read about our security policy here.
